/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */
#define SOPT5_UART1RXSRC_UART_RX 0x00u /*!<@brief UART1 receive data source select: UART1_RX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART1 transmit data source select: UART1_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTE0 (number 1), J2[18]/D14
  @{ */
#define BOARD_INITPINS_UART1_TX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_UART1_TX_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                           /* @} */

/*! @name PORTE1 (number 2), J2[20]/D15
  @{ */
#define BOARD_INITPINS_UART1_RX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_UART1_RX_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                           /* @} */

/*! @name PORTD0 (number 73), J2[6]/D10
  @{ */
#define BOARD_INITPINS_LED0_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED0_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED0_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED0_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                       /* @} */

/*! @name PORTD1 (number 74), J2[12]/D3[3]/D13/LEDRGB_BLUE
  @{ */
#define BOARD_INITPINS_LED1_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED1_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED1_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                       /* @} */

/*! @name PORTD2 (number 75), J2[8]/D11
  @{ */
#define BOARD_INITPINS_LED2_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED2_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                       /* @} */

/*! @name PORTD3 (number 76), J2[10]/D12
  @{ */
#define BOARD_INITPINS_LED3_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED3_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED3_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED3_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                       /* @} */

/*! @name PORTD5 (number 78), J2[4]/D9
  @{ */
#define BOARD_INITPINS_LED5_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED5_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED5_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED5_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                       /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_BOTON_1_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_BOTON_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BOTON_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BOTON_1_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                          /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_BOTON_2_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_BOTON_2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BOTON_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BOTON_2_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                          /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_BOTON_3_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_BOTON_3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BOTON_3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BOTON_3_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                          /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_POT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_POT_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                      /* @} */

/*! @name PORTD7 (number 80), J2[19]
  @{ */
#define BOARD_INITPINS_LED4_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_LED4_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED4_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED4_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
